name: tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '8.0']
    name: Running tests on PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP <> 8
        if: ${{ matrix.php-versions !== '8.0' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v1, phpunit:4.0
      - name: Install PHP == 8
        if: ${{ matrix.php-versions == '8.0' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2, phpunit:8.5
      - name: Install composer packages
        run: composer install --prefer-dist --no-interaction
      - name: Run phpcs
        run: vendor/bin/phpcs
      - name: Run phpunit
        run: phpunit --coverage-text